---
title: "Data Viz - Data Prep"
author: "Erik Westlund"
date: "`r Sys.Date()`"
output: ioslides_presentation
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(dplyr)
library(purrr)
library(janitor)
library(dagitty)
library(ggplot2)
library(ggdag)

# Colors from: https://tailwindcss.com/docs/customizing-colors

source("colors.R")

```

```{r fnLib, include=FALSE}

makeDag <- function(dag, labels) {
  labels <- c(
    PNC = "Comprehensive Postnatal Care",
    HQ = "Hospital Quality",
    PC = "Personal Capacity",
    WTP = "Willingness to Pay",
    T = "Trust",
    HSB = "Health Seeeking Behavior",
    R = "Risk Factors"
  )
  
  ggdag(dag) +
    geom_dag_edges(edge_color = colors$slate$`400`) + 
    geom_dag_label(aes(label = labels[name]), color = colors$gray$`900`, size = 3, fill = colors$slate$`50`) + 
    theme_void() +
    labs(title = "Causal DAG") +
    theme(
      plot.title = element_text(hjust = 0.5, size = 14, face = "bold"),
      panel.background = element_rect(fill = "white", color = NA)
    )
}

```

# Data Prep

## Causal Model

We will work backwards from our dependent variable to create a causal model.

Then we will work forwards to sim the data.

### Comprehensive Postnatal Care

```{r dv}
 dv <- dagitty('dag {
  HQ -> PNC
  PC -> PNC
  WTP -> PNC
  T -> PNC
  HSB -> PNC
  R -> PNC
 }')

basic_dag <- tidy_dagitty(dagify(
  PNC ~ WTP + HQ + PC + T + HSB + R, 
  outcome = "PNC"
))


ggdag(basic_dag, layout = "circle") + 
  theme_dag() + 
  ggtitle("Causal DAG")

```